#!/bin/bash -e
SCRIPTS="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
ROOT="$SCRIPTS/.."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PROJECT_NAME="DesperateDevs"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SOLUTION="$ROOT/$PROJECT_NAME.sln"
DNS=$PROJECT_NAME
BIN="bin/Release"

TEST_PROJECT="$ROOT/Tests/Tests.csproj"
TEST_RUNNER="$ROOT/Tests/$BIN/Tests.exe"

# build
BUILD="$ROOT/Build"
BUILD_SRC="$BUILD/src"
BUILD_DEPLOY="$BUILD/deploy"

cpe() {
  rsync -ar --include-from "$SCRIPTS/rsync_include.txt" --exclude-from "$SCRIPTS/rsync_exclude.txt" $1 $2
}

cp_dll() {
    cp "$ROOT/$1/$BIN/$1.dll" $2
}

cp_exe() {
    cp "$ROOT/$1/$BIN/$1.exe" $2
}
