#!/bin/bash -e
echo $0
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/consts"

$SCRIPTS/test
$SCRIPTS/build

# clean
rm -rf $BUILD

# create folder structure
mkdir $BUILD $BUILD_SRC

# CodeGeneration
cp_dll "$DNS.CodeGeneration" $BUILD_SRC
cp_dll "$DNS.CodeGeneration.CodeGenerator" $BUILD_SRC
cp_exe "$DNS.CodeGeneration.CodeGenerator.CLI" $BUILD_SRC
cp_dll "$DNS.CodeGeneration.CodeGenerator.Unity.Editor" $BUILD_SRC
cp_dll "$DNS.CodeGeneration.Plugins" $BUILD_SRC
cp_dll "$DNS.CodeGeneration.Unity.Plugins" $BUILD_SRC

# Logging
cp_dll "$DNS.Logging" $BUILD_SRC
cp_dll "$DNS.Logging.Appenders" $BUILD_SRC
cp_dll "$DNS.Logging.Formatters" $BUILD_SRC

# Networking
cp_dll "$DNS.Networking" $BUILD_SRC
cp_exe "$DNS.Networking.CLI" $BUILD_SRC

# Unity
cp_dll "$DNS.Unity.Editor" $BUILD_SRC

# CLI
cp_dll "$DNS.CLI" $BUILD_SRC

## Serialization
cp_dll "$DNS.Serialization" $BUILD_SRC

# Utils
cp_dll "$DNS.Utils" $BUILD_SRC
